[profile.release]
panic = 'unwind'

[workspace]
resolver = "2"

members = [
    "node",
    "asset",
    "bag",
    "bridge",
    "bundle",
    "dao",
    "exgine",
    "market",
    "primitives",
    "validator-set",
    "runtime"
]
